version: '3.8'

services:
  frontend:
    image: vyshnavijammi/hotel-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: vyshnavijammi/hotel-backend:latest
    ports:
      - "5000:5000"
