name: Deploy Stack to AWS EC2

# Trigger workflow manually or after frontend/backend builds
on:
  workflow_dispatch:
  # Optional: Uncomment to run automatically after frontend/backend workflows
  # workflow_run:
  #   workflows: ["Build & Push Frontend", "Build & Push Backend"]
  #   types:
  #     - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu                # change if your EC2 user is different
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/"

      - name: Pull images & start containers on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker-compose -f /home/ubuntu/docker-compose.yml pull
            docker-compose -f /home/ubuntu/docker-compose.yml up -d --remove-orphans
