name: Deploy Stack to AWS

on:
  workflow_dispatch:   # manual trigger (you can also tie to frontend/backend pushes)
  workflow_run:
    workflows:
      - “Build & Push Frontend”
      - “Build & Push Backend”
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy docker-compose to AWS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/"

      - name: Run docker-compose on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            docker-compose -f /home/ubuntu/docker-compose.yml pull
            docker-compose -f /home/ubuntu/docker-compose.yml up -d --remove-orphans
