name: Deploy Stack to AWS EC2

on:
  workflow_run:
    workflows: ["Build & Push Frontend", "Build & Push Backend"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu                    # Change if your EC2 user is different
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/"

      - name: Pull images & restart containers on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu                    # Change if needed
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker-compose -f /home/ubuntu/docker-compose.yml pull
            docker-compose -f /home/ubuntu/docker-compose.yml up -d --remove-orphans
